name: fraud-anomaly
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn=1.3.2
  - hdbscan=0.8.33
  - matplotlib
  - seaborn
  - jupyterlab
  - pip
  - pip:
      - tensorflow